instance_tenancy = "default"
dns_support = true
dns_host_names = true
vpc_cidr_block = "100.64.0.0/16"
enable_aws_ipv6_cidr_block = false
aws_region = "eu-west-3"
enable_vpc_flow_logs = false
Application_ID = "Spoke_VPC_Test_Run"
Application_Name ="Commercial_Bank_ID"
Business_Unit = "cb_0000000"
Environment_Type = "DEV"
CostCenterCode = "CB"
CreatedBy = "Androski Spicer"
Manager = "Kenneth Jackson"